# Generated by Django 4.1.7 on 2023-02-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.FileField(default='', upload_to='notice/images'),
        ),
    ]
