# Generated by Django 4.1.7 on 2023-02-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_notice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_father', models.CharField(max_length=50)),
                ('teacher_motheer', models.CharField(max_length=50)),
                ('teacher_degree', models.CharField(max_length=50)),
                ('teacher_university', models.CharField(max_length=50)),
                ('teacher_passingYear', models.IntegerField()),
                ('teacher_dob', models.DateField()),
                ('teacher_department', models.CharField(max_length=50)),
                ('teacher_post', models.CharField(max_length=50)),
                ('teacher_image', models.ImageField(upload_to='teacher/images')),
            ],
        ),
    ]
