# Generated by Django 4.1.7 on 2023-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='lyelmyudfe', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_userName',
            field=models.CharField(default='ntwku', max_length=5),
        ),
    ]
