# Generated by Django 4.1.7 on 2023-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_teacher_teacher_password_teacher_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='vjbvbvgtbb27', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_userName',
            field=models.CharField(default='cbakp83', max_length=10),
        ),
    ]
