# Generated by Django 4.1.7 on 2023-02-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_teacher_teacher_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='xmacabhnyt83', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_userName',
            field=models.CharField(default='bpyfk27', max_length=10),
        ),
    ]
