# Generated by Django 4.1.7 on 2023-02-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_teacher_teacher_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='bunwwdmgem9', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_userName',
            field=models.CharField(default='cisbi6', max_length=10),
        ),
    ]
